# Change these first
owner: annkuoQ # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: AnnKuoQ Blog
    url: https://annkuoq.github.io/blog/
    icon: https://annkuoq.github.io/blog/img/favicon.ico
  - name: PTS TV
    url: https://www.pts.org.tw/
  - name: PTS PLUS
    url: https://www.ptsplus.tv/
    icon: https://www.ptsplus.tv/assets/image/pts_ico.ico
  - name: PTS News
    url: https://news.pts.org.tw/
  - name: PeoPo News
    url: https://www.peopo.org/
  - name: PTS Friend
    url: https://friends.pts.org.tw/
    icon: https://friends.pts.org.tw/images/pts-membership-logo.png
  - name: KKTV
    url: https://www.kktv.me/
  - name: Gamer
    url: https://ani.gamer.com.tw/
  - name: LINE TV
    url: https://www.linetv.tw/
    icon: https://img.linetv.tw/WEB/linetv_favicon.ico
  - name: CATCHPLAY+
    url: https://www.catchplay.com/tw/home
  - name: Netflix TW
    url: https://www.netflix.com/tw/
  - name: myVideo
    url: https://www.myvideo.net.tw/
    icon: https://www.myvideo.net.tw/static/images/favicon.ico
  - name: friDay
    url: https://video.friday.tw/
    icon: https://video.friday.tw/img/favicon.ico
  - name: Broken Site
    url: https://thissitedoesnotexist.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** 是由 GitHub 提供支援的開源網站監控服務"
  introMessage: 以下是目前 PTS 各網站的服務狀況，數據來自 [GitHub Repository](https://github.com/ptstaiwan/upptime/)，我們使用 [Issues](https://github.com/ptstaiwan/upptime/issues) 回報異常事件、[Actions](https://github.com/ptstaiwan/upptime/actions) 自動化監控、[Pages](https://newmedia.pts.org.tw/upptime) 產生服務狀態頁面
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  activeIncidents: 目前異常事件
  allSystemsOperational: 所有服務皆運作正常
  CompleteOutage: 所有服務皆異常
  PartialOutage: 部分服務異常
  incidentReport: "異常事件 #$NUMBER 報告 →"
  activeIncidentSummary: 發生在 $DATE，有 $POSTS 則回應
  incidentTitle: Incident $NUMBER Details
  incidentDetails: 事件細節
  incidentFixed: 已修復
  incidentOngoing: 尚未修復
  incidentOpenedAt: 發生時間
  incidentClosedAt: 修復時間
  incidentSubscribe: 訂閱更新
  incidentViewOnGitHub: 在 GitHub 上查看
  incidentCommentSummary: $AUTHOR 在 $DATE 回覆
  incidentBack: ← 返回所有事件列表
  pastIncidents: 過去的異常事件
  pastIncidentsResolved: 在 $MINUTES 內解決，有 $POSTS 則回應
  liveStatus: 目前狀態
  overallUptime: "服務健康度: $UPTIME"
  overallUptimeTitle: 服務健康度
  averageResponseTime: "平均 Response Time: $TIMEms"
  averageResponseTimeTitle: 平均 Response Time
  sevelDayResponseTime: 過去七天 Response Time
  responseTimeMs: Response time (ms)
  up: 正常
  down: 異常
  degraded: 危險
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: 該 [開源]($REPO) 網頁由 [Upptime](https://upptime.js.org) 提供 
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
