# Change these first
owner: annkuoQ # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: AnnKuoQ Blog
    url: https://annkuoq.github.io/blog/
    icon: https://annkuoq.github.io/blog/img/favicon.ico
  - name: PTS TV
    url: https://www.pts.org.tw/
  - name: PTS PLUS
    url: https://www.ptsplus.tv/
    icon: https://www.ptsplus.tv/assets/image/pts_ico.ico
  - name: PTS News
    url: https://news.pts.org.tw/
  - name: PeoPo News
    url: https://www.peopo.org/
  - name: PTS Friend
    url: https://friends.pts.org.tw/
    icon: https://friends.pts.org.tw/images/pts-membership-logo.png
  - name: KKTV
    url: https://www.kktv.me/
  - name: Gamer
    url: https://ani.gamer.com.tw/
  - name: LINE TV
    url: https://www.linetv.tw/
    icon: https://img.linetv.tw/WEB/linetv_favicon.ico
  - name: CATCHPLAY+
    url: https://www.catchplay.com/tw/home
  - name: Netflix TW
    url: https://www.netflix.com/tw/
  - name: myVideo
    url: https://www.myvideo.net.tw/
    icon: https://www.myvideo.net.tw/static/images/favicon.ico
  - name: friDay
    url: https://video.friday.tw/
    icon: https://video.friday.tw/img/favicon.ico
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Broken Site2
    url: https://thissitedoesnotexist.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** 是由 GitHub 支援的開源網站監控服務"
  introMessage: 以下是目前 PTS 各網站的服務狀況，數據來自 [GitHub Repository](https://github.com/ptstaiwan/upptime/)，我們使用 [Issues](https://github.com/ptstaiwan/upptime/issues) 回報異常事件、[Actions](https://github.com/ptstaiwan/upptime/actions) 自動化監控、[Pages](https://newmedia.pts.org.tw/upptime) 產生服務狀態頁面
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems are operational
  degradedPerformance: Degraded performance
  completeOutage: Complete outage
  partialOutage: Partial outage
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentViewOnGitHub: View on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response time (ms)
  up: Up
  down: Down
  degraded: Degraded
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
